### ISSUE TITLE
Running blobber from docker ends up panicking  

### ISSUE THREAD

**Issue by NoSkillGuy** [0chain/blobber#232]
```
blobber2_postgres-post_1 exited with code 0
blobber_1        | 2021-06-30T05:53:41.771Z	INFO	blobber/main.go:435	Starting blobber	{"available_cpus": 12, "port": "5052", "chain_id": "0afc093ffb509f059c55478bc1a60351cef7b4e9c008a53a6cc8241ca8617dfe", "mode": "development"}
blobber_1        | 2021-06-30T05:53:41.772Z	INFO	blobber/main.go:483	Ready to listen to the requests
blobber_1        | 2021-06-30T05:53:50.007Z	INFO	handler/protocol.go:114	Adding or updating on the blockchain

postgres_1       | 2021-06-30 05:55:43.091 UTC [110] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
postgres_1       | 2021-06-30 05:57:12.861 UTC [113] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
blobber_1        | panic: runtime error: invalid memory address or nil pointer dereference
blobber_1        | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdead70]
blobber_1        |
blobber_1        | goroutine 44 [running]:
blobber_1        | main.addOrUpdateOnChain(0x0, 0x0)
blobber_1        | 	/blobber/go/0chain.net/blobber/main.go:240 +0x320
blobber_1        | main.setupOnChain()
blobber_1        | 	/blobber/go/0chain.net/blobber/main.go:211 +0x64
blobber_1        | created by main.setup
blobber_1        | 	/blobber/go/0chain.net/blobber/main.go:298 +0x184
validator_1      | 2021-06-30T06:10:41.567Z	ERROR	validator/main.go:183	Add validator transaction could not be verified	{"err": null, "txn.Hash": "8b4239bf54822a7b62b57ee61f93c320a9731de9373a995d72709cf791aa0f8c"}
validator_1      | main.RegisterValidator
validator_1      | 	/blobber/go/0chain.net/validator/main.go:183
validator_1      | 2021-06-30T06:10:46.655Z	INFO	storage/protocol.go:162	Adding validator to the blockchain.
validator_1      | 2021-06-30T06:10:59.718Z	INFO	validator/main.go:176	Transaction for adding validator accepted and verified	{"txn_hash": "801e774cb26f115fb2e2ef9ac1c3ff00b7cdad828cfd48bb8e5e12f836e4afc6", "txn_output": "{\"id\":\"7a90e6790bcd3d78422d7a230390edc102870fe58c15472073922024985b1c7d\",\"url\":\"http://198.18.0.62:5062\",\"stake_pool_settings\":{\"delegate_wallet\":\"eeb65b40e839cfe6ca403d471e98a88b793a5d5ce78e6d6bf950a431e9bb6615\",\"min_stake\":10000000000,\"max_stake\":1000000000000,\"num_delegates\":50,\"service_charge\":0.3}}"}
blobber2_blobber_1 exited with code 2

```

**Comment by NoSkillGuy** [comment]
After increasing docker resources! this error isn't coming! So closing this issue for now. will reopen this in case this occurs again.
