### ISSUE TITLE
blobber crash on intializeMinio (AWS Key ID issue)

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#371]
```


2021-09-28T02:11:37.613Z ERROR filestore/fs_store.go:171 Error with make bucket, Will check if bucket exists {"error": "The AWS Access Key Id you provided does not exist in our records."}
--
Tue, Sep 28 2021 10:11:37 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.checkBucket
Tue, Sep 28 2021 10:11:37 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:171
Tue, Sep 28 2021 10:11:37 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.intializeMinio
Tue, Sep 28 2021 10:11:37 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:164
Tue, Sep 28 2021 10:11:37 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.SetupFSStoreI
Tue, Sep 28 2021 10:11:37 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:140
Tue, Sep 28 2021 10:11:37 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.SetupFSStore
Tue, Sep 28 2021 10:11:37 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:134
Tue, Sep 28 2021 10:11:37 am | main.initEntities
Tue, Sep 28 2021 10:11:37 am | /0chain/code/go/0chain.net/blobber/main.go:76
Tue, Sep 28 2021 10:11:37 am | main.main
Tue, Sep 28 2021 10:11:37 am | /0chain/code/go/0chain.net/blobber/main.go:440
Tue, Sep 28 2021 10:11:37 am | runtime.main
Tue, Sep 28 2021 10:11:37 am | /usr/local/go/src/runtime/proc.go:255
Tue, Sep 28 2021 10:11:38 am | 2021-09-28T02:11:38.035Z ERROR filestore/fs_store.go:176 Minio bucket error {"error": "The AWS Access Key Id you provided does not exist in our records.", "bucket_name": "dev-network-blobber"}
Tue, Sep 28 2021 10:11:38 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.checkBucket
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:176
Tue, Sep 28 2021 10:11:38 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.intializeMinio
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:164
Tue, Sep 28 2021 10:11:38 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.SetupFSStoreI
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:140
Tue, Sep 28 2021 10:11:38 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.SetupFSStore
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:134
Tue, Sep 28 2021 10:11:38 am | main.initEntities
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobber/main.go:76
Tue, Sep 28 2021 10:11:38 am | main.main
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobber/main.go:440
Tue, Sep 28 2021 10:11:38 am | runtime.main
Tue, Sep 28 2021 10:11:38 am | /usr/local/go/src/runtime/proc.go:255
Tue, Sep 28 2021 10:11:38 am | panic: The AWS Access Key Id you provided does not exist in our records.
Tue, Sep 28 2021 10:11:38 am |  
Tue, Sep 28 2021 10:11:38 am | goroutine 1 [running]:
Tue, Sep 28 2021 10:11:38 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.checkBucket(0xc0003b0320, {0xc00003f128, 0x13})
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:177 +0x686
Tue, Sep 28 2021 10:11:38 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.intializeMinio()
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:164 +0x95
Tue, Sep 28 2021 10:11:38 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.SetupFSStoreI(...)
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:140
Tue, Sep 28 2021 10:11:38 am | github.com/0chain/blobber/code/go/0chain.net/blobbercore/filestore.SetupFSStore({0xc00003ea20, 0x7ffdc84db680})
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobbercore/filestore/fs_store.go:134 +0x35
Tue, Sep 28 2021 10:11:38 am | main.initEntities(...)
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobber/main.go:76
Tue, Sep 28 2021 10:11:38 am | main.main()
Tue, Sep 28 2021 10:11:38 am | /0chain/code/go/0chain.net/blobber/main.go:440 +0x905



```

**Comment by moldis** [comment]
cc @kushthedude

**Comment by cnlangzi** [comment]
@iamrz1 ignore this issue first. panic should be fine if AWS key is incorrect.
